name: Deploy to VPS

on:
  push:
    branches:
      - main  # Ganti dengan branch yang Anda gunakan

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key yang disimpan di secrets
        run: |
          echo "${SSH_PRIVATE_KEY}" > id_rsa
          chmod 600 id_rsa
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Deploy
        run: |
          ssh -i id_rsa gibran@103.102.153.62 'cd /var/www/golang-test && git pull origin main && go build && ./golang-test'
